### ISSUE TITLE
Create plan for use of IPFS Camp content in ProtoSchool

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#261]
Review IPFS Camp content and determine what would fit well within ProtoSchool and whether it makes sense as new tutorials or additions to existing materials.

**Camp content to review** 
For some of these it will become quickly apparent that the content won't translate well to ProtoSchool, either due to the format or the conent (for example, vendor-specific content if there aren't extractable IPFS tidbits), but we'll at least note that quickly in this issue before moving on. Please check off below when the course has been reviewed and suggestions have been added to a new comment in this issue. 

- [x] Core A | Understanding how the InterPlanetary File System deals with Files | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A), Slides ([PDF](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A/IPFS_Camp_Core_Course_A_Slides.pdf))| [Video](https://youtu.be/Z5zNPwMDYGg) |

- [x] Core B | Solving distributed networking problems with libp2p  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_B), Slides ([Google Slides](https://docs.google.com/presentation/d/1a_BjIM4ORQchnMNjOMO-wCDW2VS5nXeKXIbWSEqf9jY/edit?usp=sharing))| [Video](https://youtu.be/Q4IH5rWEO-E) |
- [x]  Core C | Developing Apps with IPFS API  |   [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_C), Slides ([PDF](https://github.com/ipfs/camp/files/3525750/IPFS.Camp.2019.-.Core.Course.C.-.Slide.Deck.pdf), [Google Slides](https://docs.google.com/presentation/d/1cbJD5j_jRpm3yJiE6hLIOzMn8iMhvzyci7Ut3NLjqxs/edit?usp=sharing))| [Video](https://youtu.be/6EHBOnFQJN4)|
- [x]  Core D | The lifecycle of data in DWeb.   | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D), Slides ([Google Slides](https://docs.google.com/presentation/d/1UOX-a1lCxi-LOyEOe9VEFRcxg_j93Xkywwa4Y95TJaw/edit?usp=sharing), [PDF](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D/IPFS_Camp_Core_Course_D_Slides.pdf)) | [Video](https://youtu.be/fLUq0RkiTBA)|

- [x]  Elective A | Identity on the DWeb   | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_A), Slides ([Google Slides](https://docs.google.com/presentation/d/1HbydOI0w-T_FY23zCACAyHmzDq1ZvyG2tklpPSm6OQQ))| [Video](https://youtu.be/EsLqjFEN-MM)|
- [x]  Elective B |Managing pinsets with IPFS Cluster  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_B), Slides ([PDF](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_B/slides.pdf)) | [Video](https://youtu.be/wmxaVrAFfeE) |
- [x]  Elective C |TBA (But will have cats with lasers...)  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_C) | [Video](https://youtu.be/kVzHE4MRPOM) |
- [x] Elective D |Building DApps with Textile, the iCloud for the DWeb     | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_D) | [Video](https://youtu.be/4r7_lOyv4W8) |
- [x] Elective E |Deploying IPFS Infrastructure    | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_E) | [Video](https://youtu.be/PD0e89b4NBk) |
- [x]  Elective F |Starting, Growing, and Stewarding your IPFS Community  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_F), Slides ([Google Slides](https://docs.google.com/presentation/d/1OLmSfOMjffl7z2ODxHaBcQBmyVEGdt8O7h3bxYv_VVI/edit?usp=sharing))| [Video](https://youtu.be/crTa1j3FRac)|
- [x]  Elective G |Managing Datasets with QRI  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_G) | [Video](https://youtu.be/ZN1mPBECsvA) |
- [x]  Elective H |Making the Browser a True User Agent   | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_H), Slides ([HackMD](https://hackmd.io/@dietrich/rkrZEKFRV#/)) | N/A |

**Comment by terichadbourne** [comment]
Adding a bit more detail to this one. :) 

We plan to evaluate the content from IPFS Camp and see what would fit nicely into ProtoSchool in a variety of ways: 
- linking to camp content (videos when they're released, etc.) from resources pages in related ProtoSchool tutorials
- incorporating some of the content / explanations / diagrams shared at camp into existing tutorials, such as the Decentralized Data Structures one which [we plan to split in two](https://github.com/ProtoSchool/protoschool.github.io/issues/185) or the MFS tutorial, both of which had relevant content shared in @alanshaw & @mikeal's core course
- reformatting full workshops into their own new tutorials if we can find reasonable ways for them to fit our supported formats: text-only lessons, multiple-choice lessons, and in-browser JavaScript coding exercises using IPFS (with or without file upload)

If you have ideas on specific ways we could adapt IPFS Camp content into ProtoSchool, please share them in this issue!

**Comment by realChainLife** [comment]
Hi Teri,

Great idea! I didn't get the chance to attend the IPFS Camp but going through the [camp-content-first-batch release](https://blog.ipfs.io/2019-07-22-ipfs-camp-content-first-batch/) - there's a gold mine of content that i think would make great Protoschool tutorials.

At Protoschool Nairobi, we're taking ipfs enthusiasts through the tutorials as a weekly study guide and some of the content we can add to the course include: 

* **The design of the IPFS Repo** - A repo is the storage repository of an IPFS node. It is the subsystem that actually stores the data IPFS nodes use.

* **HTTP gateways** - An IPFS Gateway acts as a bridge between traditional web browsers and IPFS.

Let me what you think and how I can hekp to get started with these if you agree.

**Comment by terichadbourne** [comment]
@realChainLife Thank you so much for your offer to help with new content, and apologies for the delay in getting back to you! I'm still working my way through the camp content, but both of these topics you're proposing sound interesting and I'd love to hear more about what you have in mind!

I've been working on some clearer documentation for the process of building effective tutorials, not just how to build the tutorial in our repo ([already documented here](https://github.com/ProtoSchool/protoschool.github.io#protoschool)) but how to create great learning experiences and what features are supported by our platform. The easiest way to see my new additions (still very much a work in progress) is to [check out the diff here](https://github.com/ProtoSchool/protoschool.github.io/pull/286/files#diff-04c6e90faac2675aa89e2176d2eec7d8). To get started, I'd recommend that you read through both sets of instructions linked above, check out the [existing new tutorial proposals](https://github.com/ProtoSchool/protoschool.github.io/issues?q=is%3Aopen+is%3Aissue+label%3Anew-tutorial)  to see if there's any overlap, then [open issues for each new tutorial proposal](https://github.com/ProtoSchool/protoschool.github.io/issues/new?assignees=&labels=new-tutorial&template=tutorial-proposal.md&title=New+Tutorial%3A+%5BProposed+title%5D) that doesn't already have an issue to add to. (Based on a quick glance through existing issues, I expect you'd be adding two new issues, one of each of your bulleted suggestions.) 

If you spotted specific content from IPFS Camp ([repo](https://github.com/ipfs/camp)) that's relevant and could help inform either of these tutorials, you should definitely include links in your issue, along with links to any other helpful documentation that could be drawn on for the content. You'll see in the reference materials about building tutorials that there are a few different types of lessons available: code challenges (with or without file upload), text-only lessons, and multiple-choice lessons (new feature). I'd love to hear more in your issues about which formats you think would be most relevant for this content. We can use each issue as a place to solicit input from peers before you get started building and ensure there's a solid content outline that fits cohesively into the ProtoSchool curriculum and supports a beginner-friendly learning experience with appropriate scaffolding. 

I'm really excited to learn more about the content you have in mind! 🎉 Please let me know if you have any questions about the documentation or would like to schedule some time to chat.

**Comment by terichadbourne** [comment]
**Core Course A: Understanding How IPFS Deals with Files** (led by @alanshaw & @mikeal):

- Video: https://youtu.be/Z5zNPwMDYGg
- Slides:  https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A/IPFS_Camp_Core_Course_A_Slides.pdf
- Course readme: https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A

Potential uses in ProtoSchool:
- [ ] New tutorial: Anatomy of a CID (including hashing details) 
- [ ] UX: Link to said new tutorial from the [CID Inspector](https://cid.ipfs.io/)
- [ ] UX: Link to [CID Inspector](https://cid.ipfs.io/) from lessons where result is a CID (#299) - similar to what we now do with IPLD Explorer in DAG lessons
- [ ] Tutorial improvement: Use some of the pics or images from the verifiability section in the location v content addressing portion of our Decentralized Data Structures tutorial, which we're [planning to split in two](https://github.com/ProtoSchool/protoschool.github.io/issues/185)
- [ ] Tutorial improvement: Add lots of the content from the Merkle DAG section to the latter part of the Decentralized Data Structures tutorial, which we're [planning to split in two](https://github.com/ProtoSchool/protoschool.github.io/issues/185)
- [ ] Tutorial improvement: Look at the MFS gotchas from the end of the talk and see what should be added to our MFS tutorial
- [ ] Tutorial improvement: Link to the video from resources page in our MFS tutorial and Decentralized Data Structures tutorials

**Comment by terichadbourne** [comment]
**Elective F |Starting, Growing, and Stewarding your IPFS Community** |  [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_F), Slides ([Google Slides](https://docs.google.com/presentation/d/1OLmSfOMjffl7z2ODxHaBcQBmyVEGdt8O7h3bxYv_VVI/edit?usp=sharing))| [Video](https://youtu.be/crTa1j3FRac)|

Nothing here to add as tutorial content, but...  
- [ ] We should get some of the tips for organizers documented in writing in our organizing repo. Noted as Item E in https://github.com/ProtoSchool/organizing/issues/58

 **Elective C | Cat roulette**  | [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_C) | [Video](https://youtu.be/kVzHE4MRPOM) 
- Doesn't appear to have consumable content in an appropriate format for ProtoSchool

**Comment by terichadbourne** [comment]
**Core Course D: The lifecycle of data in the DWeb**
-  [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D)
- Slides ([Google Slides](https://docs.google.com/presentation/d/1UOX-a1lCxi-LOyEOe9VEFRcxg_j93Xkywwa4Y95TJaw/edit?usp=sharing), [PDF](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D/IPFS_Camp_Core_Course_D_Slides.pdf)) 
- [Video](https://youtu.be/fLUq0RkiTBA)

This one addresses a lot of very common questions about what happens after you add file to IPFS. More than some other resources it also focuses on blocks specifically as opposed to files (which our MFS and Files tutorials focus on). The lecture format used at IPFS Camp would lend itself well to a text or multiple choice format but likely not coding challenges. There are also lots of helpful graphics in the deck that would be great to incorporate. 

Potential uses in ProtoSchool: 

- [ ]  Tutorial improvement: Link to the video from resources pages from... 
      - Decentralized Data Structures tutorials (great more advanced follow-up on the concept of sharing data without making learners code)
      - All of the coding challenges as a "you've added a file to IPFS, now what?"
- [ ] New Tutorial on the lifecycle of data to include: 
   - providing (I have these blocks)
        - distributed discovery, locating content-addresses data with Kademlia / DHT (distributed hash table)
   - getting (I want those blocks) 
       - Bitswap for trading blocks, as illustrated in the preso by the dance/skit
       - Wantlists, messages, sessions, verified data
   - pinning (keep these blocks)
       - garbage collection 
       - recursive pinning (block party tool was helpful for demonstrating this but might not have quite the self-evident UX yet to stand without a presenter)
      - reciprocal co-hosting
   - deleting (do not want)
       - local-ness of deletion
There's a ton of great content here and it's possible some of it may need to be pulled out into multiple tutorials to keep things manageable. We can get into more details when setting up an outline, but please let me know @olizilla if you've already had thoughts on a clean breakdown here, or if you think I'm wrong that multiple-choice is the most appropriate format for this content.

**Comment by terichadbourne** [comment]
**Core B: Solving distributed networking problems with libp2p**  

- [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_B)
- Slides ([Google Slides](https://docs.google.com/presentation/d/1a_BjIM4ORQchnMNjOMO-wCDW2VS5nXeKXIbWSEqf9jY/edit?usp=sharing))
- [Video](https://youtu.be/Q4IH5rWEO-E) 

Because of the hands-on format of this workshop, which asked participants to build a chat app on their local machine, it doesn't lend itself directly to a ProtoSchool tutorial. However, there are plenty of nuggets in the slide deck that could be taught.

There are probably a couple of options here: 
A.  pull out core concepts from the slide deck and teach them in a multiple-choice format
B.  add validation support for libp2p to ProtoSchool   and then create a tutorial with in-browser coding/configuration challenges (see issue #229 ) - this still wouldn't directly mirror the approach taken in the workshop, which requires one's own command line and development environment

Either of these options would require support from the libp2p team.

Some of the key concepts covered in slides/speaker notes that might be relevant: 
- Transports 
      - Selecting
      - Configuring
- Connecting to peers
      - Multiaddrs
      - reusing connections
      - stream multiplexing (muxers)
      - encryption
- Creating a protocol
- Peer discovery / DHT / Kademlia 
      - random walk 
      - broadcasting messages: floodsub v gossipsub
      - provider records

Note that there's a lot of overlap here between DHT coverage in Core Course D (Lifecycle of Data in the DWeb) and this course. Is there any reason that IPFS-flavored DHT education and libp2p-flavored DHT education would need to be distinct from each other? 

@jacobheun as the lead for this IPFS Camp course and the author of issue #229 on adding validation support, I'd love your input on what feels most feasible for incorporating your content into ProtoSchool. Note that there's new documentation available on the [platform capabilities/limitations](https://github.com/ProtoSchool/protoschool.github.io/blob/code/DESIGNING_TUTORIALS.md#the-capabilities-and-limitations-of-our-platform). What feels like the right starting point?

**Comment by terichadbourne** [comment]
**Core C: Developing Apps with IPFS API**  
- [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_C)
- Slides ([PDF](https://github.com/ipfs/camp/files/3525750/IPFS.Camp.2019.-.Core.Course.C.-.Slide.Deck.pdf), [Google Slides](https://docs.google.com/presentation/d/1cbJD5j_jRpm3yJiE6hLIOzMn8iMhvzyci7Ut3NLjqxs/edit?usp=sharing))
- [Video](https://youtu.be/6EHBOnFQJN4)

There are a lot of great nuggets in here that haven't yet been taught in ProtoSchool, but the hands-on workshop format used at IPFS Camp may not lend itself well to the current  [platform capabilities/limitations](https://github.com/ProtoSchool/protoschool.github.io/blob/code/DESIGNING_TUTORIALS.md#the-capabilities-and-limitations-of-our-platform), such as doing everything in-browser in js-ipfs. We could certainly add some relevant content in reading / multiple-choice lessons even if we're not able to replicate the coding challenges of building an app. 

Some key topics covered in the slide deck:
- Where to run IPFS (provisioning)
     - Backend service: self-hosted or using existing cloud providers (Infura, Pinata, etc.) 
      - Embedded IPFS node shipping w/ your app
            - go-ipfs vs js-ipfs: differences / interop 
- APIs (note that we can describe these in text but the rest of ProtoSchool teaches js-ipfs due to our in-browser needs)
    - CLI
      - HTTP API 
      -embedded  js-ipfs API in the browser
      - API fallback 
- Working with Data 
      - picking an API based on data type - regular files (use Files)  v complex data structures (use DAG) - this is now covered to an extent in https://proto.school/#/regular-files-api/01
      - add and cat (already well covered in other tutorials re files of dag apis, but no coverage of  CLI or reading via the gateway)
- Naming / IPNS
     - naming and publishing with keys 
     - mutable pointer to immutable content path
     - _I'm not sure to what extent we can teach IPNS through js-ipfs browser-based challenges, but IPNS is a key topic people want to know more about, so I'd love to at least teach it in text/mult choice_

@lidel @hugomrdias I'd love your input on whether any of this content could work well as coding challenges (using in-browser js-ipfs) or if we should hone in on text/multiple-choice options for teaching about how IPFS can be used inside applications (or honing in specifically on IPNS).

**Comment by terichadbourne** [comment]
**Elective A: Identity on the DWeb**   
-  [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_A)
- Slides ([Google Slides](https://docs.google.com/presentation/d/1HbydOI0w-T_FY23zCACAyHmzDq1ZvyG2tklpPSm6OQQ))
- [Video](https://youtu.be/EsLqjFEN-MM)
- See also [Identity Manager Concept](https://github.com/ipfs-shipyard/pm-idm/blob/master/docs/idm-concept.md) on GitHub
- See also [Nomios website](https://nomios.io/)

This session introduced Identity Manager (IDM) and walked people through the process of integrating IDM to provide authentication and signing into a simple decentralized chat app. There's some very interesting content here, but I'm not sure if Identity Manager/Nomios are far enough along in development to be taught yet. As best I can tell the concepts here would be most appropriate for text / multiple-choice lessons if they were implemented in ProtoSchool. (However, docs say "there will be a reference IDM Wallet written in JavaScript, suitable to use inside a browser" so perhaps some coding challenges would be possible if useful.)

Key concepts: 
- Identity is out of our control on centralized networks
- Self-sovereign identity (SSI) for ownership and portability
- Decentralized Identifiers (DIDs) resolving to DID Documents
- DID Methods (CRUD) vary across target systems (Bitcoin, Ethereum, IPFS, etc.)
- Verifiable credentials 
- Future developments
      - DIDs and verifiable creds are meant to be interoperable but currently different methods have to integrate with different wallet SDKs, people are using multiple wallets to represent almost identical data/identities
      - Nomios is a reference UI identity wallet built on new Identity Manager spec meant to be more genuinely interoperable

@dominguesgm I know you've worked on IDM in the past so I'd love your take on what seems like it could fit well in ProtoSchool.

**Comment by terichadbourne** [comment]
**Elective B: Managing pinsets with IPFS Cluster** 
- [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_B)
- Slides ([PDF](https://github.com/ipfs/camp/blob/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_B/slides.pdf)) 
-  [Video](https://youtu.be/wmxaVrAFfeE)

This course was very much a command-line based hands-on workshop on operating and using IPFS Cluster to orchestrate a common pinset among multiple IPFS nodes. My impression is that the format of this workshop doesn't lend itself well to ProtoSchool (where we can either do text/multiple-choice lessons or js-ipfs coding challenges in the browser) because I don't see a clear JS implementation at first glance and assume we wouldn't be able to replicate the experience of connecting to multiple peers from within ProtoSchool, but I'd love for folks more familiar to correct me if I'm wrong. 

It would certainly be possible to teach about some of the benefits of Cluster in text/multiple-choice format, but as noted in the prereqs for the workshop, that would require first teaching IPFS concepts such as pinning (likely to be included in the output from Core Course D) and libp2p peers and swarm (no libp2p content at present and coding challenges would require the addition of libp2p validation under the hood). 

My gut is that we should continue down the road of adding IPFS and libp2p content mentioned above, then circle back with the Cluster team to see whether there's additional content that would be useful and feasible once that scaffolding is in place. @lanzafame @hsanjuan I'd love your thoughts.

**Comment by hsanjuan** [comment]
> Elective B: Managing pinsets with IPFS Cluster

@terichadbourne your gut is right. The main contribution that could come from our side to something like Protoschool is about dynamic data and [Merkle]-crdts . That would be something cool to do once you know all the basics... Something for the future though

**Comment by terichadbourne** [comment]
**Elective D: Building DApps with Textile, the iCloud for the DWeb**     

- [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_D) 
- [Video](https://youtu.be/4r7_lOyv4W8) 
- [Slides](https://github.com/textileio/ipfs-camp-2019/blob/master/workshop/markdown.md), which require Reveal.js to view correctly
- See also [Textile docs site](https://docs.textile.io/)

This hands-on, command line workshop use Textile's developer suite to introduce participants to tools and techniques that facilitate building real-world apps and libraries on top of IPFS. Topics covered include: seeds, wallets, threads, schemas, mills, DAGs, etc.

Based on the format of this preso in building a full dapp, I don't think it would lend itself easily to ProtoSchool's capabilities, and the Textile team has great documentation on their site for the basic concepts taught here. I'd recommend skipping Textile content in our immediate efforts but would be _very_ happy to consider proposals from folks who'd like to add it down the road where relevant, especially after we have more of our core IPFS content covered to provide more scaffolding.

**Comment by lidel** [comment]
> Core C: Developing Apps with IPFS API
> [..] @lidel @hugomrdias I'd love your input on whether any of this content could work well as coding challenges (using in-browser js-ipfs) or if we should hone in on text/multiple-choice options for teaching about how IPFS can be used inside applications (or honing in specifically on IPNS).

Theory would be mostly text based. A subset of coding challenges that relied on js-ipfs running on a page could be translated into ProtoSchool format, but I don't believe IPNS changes landed yet (@hugomrdias  and @aschmahmann work on it). We also probably don't want to invest time in teaching people how to use centralized ws-star when [we plan to deprecate it](https://github.com/libp2p/js-libp2p/issues/385). Hope this helps.

**Comment by dominguesgm** [comment]
*Elective E: Deplying IPFS Infrastructure*

* [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_E)
* [Video](https://www.youtube.com/watch?v=Z5zNPwMDYGg)


The course covers how to create an IPFS cluster in the cloud. It is mostly command line based. Some non IPFS specific topics are covered in the first half of the session, like creating Digital Ocean droplets, using ssh and creating a key to use ssh.

This course uses Digital Ocean in order to host an IPFS infrastructure, which may be an issue given it requires creating an account on Digital Ocean and providing payment information.

IPFS related information (installation and work) starts at the 26 minute mark. Some IPFS node settings are discussed, such as:

* MDNS, for peer discovery
* Routing options
* Node discoverability by controlling the range of connections
* Dealing with NAT

At the current stage for ProtoSchool, with no tutorials on command line IPFS, the contents on this course seem to be too advanced to be relevant to be included here.

**Comment by dominguesgm** [comment]
**Elective G: Managing Datasets with QRI**

* [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_G)
* [Video](https://www.youtube.com/watch?v=ZN1mPBECsvA)

This course gives an introduction to QRI for managing datasets and how it interacts with IPFS. It's a pratical, command line based course which teaches the basic usage of QRI, how handles adding and querying datasets, as well as how updates are managed.

This elective seems to be indirectly related to IPFS contentwise, in a way where I don't feel like there is content that could be extracted for use in ProtoSchool. It can, however, be showcased as a relevant IPFS usage "in the wild" if we end up creating some sort of Resources page for relevant projects, to show users what can be built with IPFS.

**Comment by dominguesgm** [comment]
**Elective H: Making the Browser a True User Agent**

* [Course Repo](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/ELECTIVE_COURSE_H)
* [Slides](https://hackmd.io/@dietrich/rkrZEKFRV#/)

This course discusses the browsers place in the distributed web, and how a browser can be adapted or created in such a way that it can make use of the distributed web.

Some of the approaches discussed are:
* Browser extensions (example given is Patchfox)
* Localhost Bridge
* Electron

One disadvantage for analyzing this elective course is that we do not have a video recording of the session, and can only base ourselves off of the course slides. The slides mention a practical section of the course.

Personally, I don't see a way in which the content of this elective course could be applied to ProtoSchool. The format of the practical section would not lend itself well to ProtoSchool's format and the theoretical section at the beginning is more of an exploration of what could be the browser's place in the future of the DWeb and not any particular learnable concept.

**Comment by terichadbourne** [comment]
Closing out this survey issue in favor of the individual issues now created for all actionable proposals: 

**Core Course A** 
- [x] #332 Tutorial improvement: Link to the video from resources pages in other tutorials
- [x] #299 UX: Link to CID Inspector from lessons where result is a CID
- [x] #329 New tutorial: Anatomy of a CID (including hashing details) (#329)
- [ ] #330 UX: Link to said new tutorial from the [CID Inspector](https://cid.ipfs.io/) (#330)
- [ ] #185 Current plan to split Decentralized Data Structures Tutorial in two: 
    - [ ] Tutorial improvement: Use some of the pics or images from the verifiability section in the location v content addressing portion of our Decentralized Data Structures tutorial
   - [ ] Tutorial improvement: Add lots of the content from the Merkle DAG section to the latter part of the Decentralized Data Structures tutorial
- [ ] #331 Tutorial improvement: Look at the MFS gotchas from the end of the talk and see what should be added to our MFS tutorial 

**Core Course D**
- [ ]  #333: Link to the video from resources pages
- [ ] #332 New Tutorial on the lifecycle of data

**Elective Course F**
- [x] Add video to resources page for chapter leaders 
- [ ] ProtoSchool/organizing#58 - Item E - Document best practices for running live workshops based on our tuturials

@johnnymatthews flagging this issue as complete so you snag any useful notes for docs site updates. There'll be more content that's useful for you than us since you don't have all of our formatting limitations.
