### ISSUE TITLE
Launch Filecoin tutorial (week of 6/29)

### ISSUE THREAD

**Issue by terichadbourne** [ProtoSchool/protoschool.github.io#453]
- [x] add `0007` to `all` and `featured` in courses.json - done in #466
- [x] remove `"hidden": true` in tutorial.json - done in #466
- [x] link from Rachel's filecoin blog post on verifiable storage Monday https://filecoin.io/blog/filecoin-features-verifiable-storage/
- [x] announce via ProtoSchool newsletter (Tue or Wed)
- [x] announce via ProtoSchool Twitter (Tue or Wed)
- [x] announce via Filecoin blog post (Wed or Thu)
- [x] implement course filter (when ready this week) - WIP #457
- [ ] announce Filecoin course on Twitter (next week)

**Comment by terichadbourne** [comment]
@zebateira I just added the new tutorial to the listings because I discovered an opportunity to link to it in a super-related blog post that just went out. We’ll launch the courses separately but still soon. See updated rough schedule above.

**Comment by terichadbourne** [comment]
Filecoin tutorial has launched. Can be shared in a number of ways: 
- Direct link to Verifying Storage on Filecoin tutorial: https://proto.school/#/verifying-storage-on-filecoin
- Link to our new Filecoin course which includes it: https://proto.school/#/tutorials?course=filecoin
- Link at the end of Rachel's Filecoin blog post on verifiable storage: https://filecoin.io/blog/filecoin-features-verifiable-storage/
- Announcement tweet from ProtoSchool: https://twitter.com/ProtoSchool/status/1280212644360839182
- Announcement tweet from Filecoin: https://twitter.com/Filecoin/status/1280910563590246405
